language: ruby
addons:
  firefox: '66.0'
rvm:
- 2.5.0
- jruby
before_install:
- gem install bundler
- gem update bundler
- rvm install ruby-2.5.0
- bundle install
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: EDPS2qyrw2JSdbLMVQpjDBtXQlo5PJPJnQED6Nmnh5t2/US+sl+iuQ1bdZwFPREOlVj1pjtAl9pr2G1BXQEa/OMFqGkJMePHEq7p76YNp+1GkO/8vy6nQJYeq/LGGdEZTL1bahPM9n1nlTPXd+x8Fow+FtOOw8PjDRdcfueqZSYAdbCfW5rD54JJvHtBJWP9MGFjurgMiX/vA49aUS5l9xJDsCHIRSDvZ0wQ/Q9oIHM0aLeoDntTXQDbD9fjjaNtEJBd90kKU8kI24Tkr5Zrh6FdnUAJDuTKS2RdRceZprMgJgOgzib4XKmBtt8PwF7QprTNr/t+BeCuXc/BZVa8MGy1HsXAwNtZl45wmyhJtced2ER5f7Amha4lulV3We1oOvRN78NQSgeoV46vvJ93BRPbd5EjxM14LRXXjZRX8oNyFHM6tqr/aA0+59rnpJSoZrphPqZfagvlN9YN94bGKrGxmS1IgNgq4Ap7oW3asy5VGtkj6OWvRmR9amk1ozUDtPPXuTx8LfziginNZkz6IvdP+PjuJq/1gz2vLQILOOAwkgzj/WjlwyWkKhAE6EuaWD2tKNYzlqeQydlz1I6rXzdoDPkCvlQL4Tv2TkBPREMkFzh4iIZrZo1J/ly3g13Q0zgvGGCJUnSglnzqRTy3284G2GuGvtxsOtU0Abq9b40=
  app: makers-acebook-creators
  on:
    repo: matthewwhitaker/acebook-creators
