language: ruby
addons:
  firefox: '66.0'
rvm:
- 2.5.0
- jruby
before_install:
- gem install bundler
- gem update bundler
- rvm install ruby-2.5.0
- bundle install
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: TYCzeYR9rHoqAbUf+cXMkcRtA6e3FIaRGe2ZqrkNJaFhoRcmLIrSOeECykoSo+Sy6ZjWbG9Wcjz0vaQ1L5bDUh2SfVpz0EbITSFp7w1TOcr1j9MOLUvi6NRuXmvcHOZLERPtUgabIiBRKTaLHQ6UuDfLGEsgIffACgDoub6p7zoAlhXee0yKNSJKVfCT2AgBAJxD1y/X63QlD422jrWXXG1egkS3p4jI9YprX9AyRUrTG+80k6u+6jPgf89p8eBPKbS6L7qjtMZuPGanuDv/UX9W4LM+hAP6miKqHdah9xgDPaGx64/zu7E5tN66Bkuza6TffavpD+L3Tbu5TU2a0Imfppyw4NHhjmj0zXfXEtMGoBMhVwv4aN1MB0SzRy/PWtnln/vEb/vrqBAIoe+Pzk9Owk/qMzqQSsyqabknrWRoAhmJlhlRwTRVtLHw20gQC96sD0HJ/0Xwub8SImlS4kErq6d6Ec4eorX6vsVtv3tTA9PhadUYDi1S7XWXP44eC9a4GgbQLZPGlS3tMM20p8CVnzNagGf13284Mg2CrvDA//MEaEYYSP58FL1Fkj3G9L6CnZ5HZD90YayOpKjbqS1whPvU4KExnsPz9+Czk5B5YV3OZIFl3dc3WMqsKVOcs7k7L3R+/oDMRdInyLAkk/SZILA51vw1Dn/QIsOactY=
  app: makers-acebook-creators
  on:
    repo: matthewwhitaker/acebook-creators
env:
  global:
    secure: iJ534yIye/Tl7WycS/1DlMhNEfa+HtwcVgWmuA/5egKJ9rJ0/R84DAyLI2hIwx7RyRotOZGK+ho1aHsTaTTu5X5X3MVbwAHPFj53rOb4KfKTOPNi8yCmsKLyocH7g88RA6YAshGPSbVsHSwkUpM3I305F1NGWwrdDOhu1h8eAvMjiGJuKS+l4CvFcRxfPZRUvGvhGRDi+o4sj7utDw8QbdBgnAjb2pXoMvPHOSrgeL9fbm/5MH1Ot5Ctiu4QLYQv8yDsSglIM4/yEWaPErbUAX2ff3tFwgRIiqsVuPV7iYunDULjQx41FyTzEmJge5MvvUjEcDYRvZdL5gvzUgNbS01cwz57l+esEZqVBW3kyyhafFgTf9gvPLXKHV2S+sXeiuPQmH0INlLJ1RafKJyZz6Gvl6s8CP5+NFaMxcdZC81pBAmcCuMWGY/gTGxe4yjr028V1sv0Hi4wsG4aOdwftHPO2YrwLD3NNtfNtpqMFNP9xO3HxtpaqFzKFhRGRruhHLcoATI5aaAzDbcLhtocnz9PpAaUISyn1oTcvCkSfr9WOfVIauzohkNYnCwXtFjauZSAUvnR5XkcArM7Zt2G6t3QDHCmwfPGKKEm5UtsG8zWIUxRUO3l2YuMYtnH0Y5gVu9m038nahyecIOjK/TmcYqkKaZMYfEaZtN7FC0b8BE=
