language: ruby
addons:
  firefox: '66.0'
rvm:
- 2.5.0
- jruby
before_install:
- gem install bundler
- gem update bundler
- rvm install ruby-2.5.0
- bundle install
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: IO5LpgG0flvktu/T3FptOctlErpm3SApDSt7Lx7B96pNnL1fDBdGrPTV2wg1mQ/c/dmzwqyNvIFoM6H/sP4xeEjxO0s+LME1izWw1CSX3XNeEJOz8GNECwNu5ND5r0shHFqhTtr0ueJ0iA/kI4ga5BmEOwwL83ARynydqd2mFtjXGUZ49q75LP5ek56bFJr++z20L8VbxUUM+Qp+jEhJZOOuspu55eYJdRRo09CllXkZtA0kD4Qw4IDzlKfA7T9JEqfJjjbJjivtczFkErRcK6XuIzJZHY8I68DPCdApgKxhC1SOpOfSJbgQF8C/jilTJG1rrpGxgrsDCfY+NwT8eKTmKSqjZs/kYRJQlEkU+IfBnv3uHvSg9/RZBMc3Bjnzv0+EUKtbJBkaUnqMp1lr4clqeEXKNUQeEnP3xcZ8+cu8oXW+hqRfcmxxz5ExBwLyqeBKXdvv4RiGavaTclxgO+SBwKtw+zK9DCcM900SJrdOm2lN48cuhhUctt4h7gsUssjayydVQBB2ekRUiLL52YCfMo5VwBaDgDV9Y8QgOgaM4+wVJi3sreKWkQPwU/cmrkglEzn3KBEgZzwFVH2CZ3Rb5IsaSzXv89Qg/uS+1y6YHifbs/2Q+GzLJXUOCnVxv0RsipOwXy9FvEbkNCDwHGEW94kh8B8ElAcfHweg7cI=
  app: makers-acebook-creators
  on:
    repo: matthewwhitaker/acebook-creators
