language: ruby
addons:
  firefox: '66.0'
rvm:
- 2.5.0
- jruby
before_install:
- gem install bundler
- gem update bundler
- rvm install ruby-2.5.0
- bundle install
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: SDmzNJ2KmJCCJwyGdpggFZXyfNhfsLXArx9wAiSFEFRxCCDGyW+21Ob+nLTMJrADQHu9PKb3sB8I4AragJBWlh2BrYvbXvXxdOBZh7SXQflSmIRRmvxGCvmR3u5mY/5zXJp6emXZCYzC7OKU/OIYA8qL9hsZcZETftPIqnanrlyb9IdCtZ2q4TP3oA0b/gQZkDP/vJgl/bos22bETIUndfaOofR/3pzAykKGIe92mEGFhI26VifPWK8Ij9M5VkqUfkTCSQALVHXROmIy5/u3QDCoxd069Yb5uz4JIe7KXMCicLgZmxAxbXQjij4hDjNu0fwg0ZZrX9VFeygycM8f/MqB0eRCmbt0wFYDkU95qM8dfBFnV5fq2FByzkuM1/6A6rW2O/Sop4JaQ/Ib8Py6SbSb2f6EimPHqwNqvpb3jhPtfXpuRx0owI7jHqQkYAWLYlFnZzFT4TxUx5XjRETlNwdt8KwS33jFHu42WxoRWFX1MK6L4MUz1/e4WE02mW3swF/DJk9Gson8oEQSEr6+eIyubqWEYXrhR9AD4m4NQVwdGdwnZyEHzjmXNJ8X+dipMcm1LnaCkLPlqoxeB3CmzSFpTat9Bp1w3aRnVCZFm5WyWmune5rANlyrXyO0vPqxZ060lYM+sLYUxdH9eoziwUe3aUsxOvU9lKh9mneSSok=
  app: makers-acebook-creators
  on:
    repo: matthewwhitaker/acebook-creators
